---
- name: Update and upgrade Ubuntu servers
  hosts: 127.0.0.1
  #connection: #local
  become: yes
  become_user: root

  tasks:
    #- name: Update package cache
     # apt:
      #  update_cache: yes

    - name: Install nala package
      apt:
        name: nala
        state: present
