---
- name: Update and upgrade Ubuntu servers
  hosts: all
  sudo: true
  sudo_user: root

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install nala package
      apt:
        name: nala
        state: present
