---
- name: Update and upgrade Ubuntu servers
  hosts: all

  tasks:
    #- name: Update package cache
     # apt:
      #  update_cache: yes

    - name: Install nala package
      become_user: root
      apt:
        name: nala
        state: present
