---
- name: Update and upgrade Ubuntu servers
  hosts: all #localhost
  #connection: #local
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install nala package
      apt:
        name: nala
        state: present
