---
- name: Update and upgrade Ubuntu servers
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install nala package
      apt:
        name: nala
        state: present

    - name: Append .bashrc file for all users
      lineinfile:
        path: "/home/{{ item }}/".bashrc
        line: "echo '# package manager alias'"
        line: "echo 'alias apt='nala'"
        line: "# The white space after the o in sudo is intentional"
        line: "alias sudo='sudo '"
        create: yes
        insertafter: EOF
      with_fileglob: "/home/*"
